name: "auto-labeler"
description: "Composite action for label automation"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: labeler
      uses: actions/labeler@v5
    - name: size-label
      uses: "lablup/size-label-action@master"
      env:
        GITHUB_TOKEN: "${{ inputs.GITHUB_TOKEN }}"
        IGNORED: "**/*.lock"
    - name: auto-label-in-issue
      uses: lablup/auto-label-in-issue@1.7.0
      env:
        GITHUB_TOKEN: "${{ inputs.GITHUB_TOKEN }}"
